apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "login.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "login.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "login.fullname" . }}
    spec:
      containers:
        - name: login
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi