apiVersion: v1
kind: Service
metadata:
  name: {{ include "vehicle.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5002
      nodePort: 30002
  selector:
    app: {{ include "vehicle.fullname" . }}