apiVersion: v1
kind: Service
metadata:
  name: {{ include "appointment.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5003
  selector:
    app: {{ include "appointment.fullname" . }}